-- MySQL Script generated by MySQL Workbench
-- Fri May 17 14:02:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DER_EcoAid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DER_EcoAid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DER_EcoAid` DEFAULT CHARACTER SET utf8 ;
USE `DER_EcoAid` ;

-- -----------------------------------------------------
-- Table `DER_EcoAid`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_EcoAid`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_categoria` VARCHAR(255) NOT NULL,
  `descricao_categoria` VARCHAR(255) NULL COMMENT 'Descrição da categoria, por exemplo, produto eletronico compõe produtos com placas impressas na sua composição.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_EcoAid`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_EcoAid`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_EcoAid`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_EcoAid`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(255) NOT NULL COMMENT 'Nome do produto para melhor busca.',
  `tipo_produto` VARCHAR(255) NULL,
  `descricao_produto` VARCHAR(500) NULL,
  `condicao` VARCHAR(255) NULL,
  `valor` DECIMAL(8,2) NULL,
  `categoria_id` BIGINT NULL,
  `usuario_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`categoria_id` ASC) ,
  INDEX `fk_tb_produto_tb_usuario1_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `DER_EcoAid`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `DER_EcoAid`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
